// ─────────────────────────────────────────────
//  Smartory — Order Service
//  Fetches smart shopping plans (order lists)
//  generated by the planner agent.
// ─────────────────────────────────────────────

const BASE_URL = "http://127.0.0.1:8000";

// ─── Types ────────────────────────────────────

export type OrderItem = {
  item: string;
  reason: string;
  have_ordered: boolean;
};

export type Order = {
  id: string;
  user_id: string;
  order: OrderItem[];
  created_at: string;
  estimated_date_to_order: string;
  is_complete: boolean;
};

export type IncompleteOrdersResponse = {
  status: "success" | "error";
  data: Order[];
};

// ─── API calls ────────────────────────────────

/**
 * Fetches all open (incomplete) order plans for the authenticated user.
 */
export async function fetchIncompleteOrders(
  token: string,
): Promise<IncompleteOrdersResponse> {
  const response = await fetch(`${BASE_URL}/orders/incomplete`, {
    method: "GET",
    headers: {
      accept: "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(
      `Failed to fetch orders: HTTP ${response.status}${text ? ` — ${text}` : ""}`,
    );
  }

  return response.json() as Promise<IncompleteOrdersResponse>;
}
